# -*- ruby -*-

require "pkg-config"
require "native-package-installer"

case RUBY_PLATFORM
when /mingw|mswin/
  task :default => "nothing"
else
  task :default => "dependency:check"
end

task :nothing do
end

namespace :dependency do
  desc "Check dependency"
  task :check do
    unless PKGConfig.check_version?("opencv-glib")
      unless NativePackageInstaller.install(:debian => "libopencv-glib-dev",
                                            :redhat => "opencv-glib-devel")
        exit(false)
      end
    end
  end
end
